---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: sh -l -c 'dart --version'
    register: dart_test_output
  - name: dart --version
    debug:
      msg: '{{ dart_test_output.stdout }}'
