---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ dart_install_dir }}..
  become: true
  ansible.builtin.stat:
    path: '{{ dart_install_dir }}'
  changed_when: false
  register: dart_binary
- name: Downloading and installing dart
  when: not dart_binary.stat.exists
  block:
    - name: Downloading {{ dart_url }} to {{ dart_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ dart_url }}'
        dest: '{{ dart_tmp_zip }}'
        mode: '644'
        checksum: '{{ dart_checksum }}'
    - name: Mkdir {{ dart_install_dir }}...
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dart_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ dart_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ dart_tmp_zip }}'
        dest: '{{ dart_install_dir }}'
        creates: '{{ dart_sdk_install_dir }}'
    - name: Chmod 755 bin dirs
      with_items:
        - '{{ dart_sdk_install_dir }}'
        - '{{ dart_sdk_install_dir }}/bin'
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '755'
  always:
    - name: Rm -f {{ dart_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dart_tmp_zip }}'
        state: absent
- name: Link {{ dart_sdk_link_dir }} to {{ dart_sdk_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ dart_sdk_install_dir }}'
    dest: '{{ dart_sdk_link_dir }}'
    state: link
- name: Add to login shell path
  become: true
  become_user: root
  with_items:
    - f: dart.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
